import { expect, test } from '@playwright/test';
import path from 'node:path';

const sampleThree = path.resolve('public/samples/sample-three-tests.pdf');
const sampleFigure = path.resolve('public/samples/sample-figure.pdf');

test('tapping a choice grades it and shows the explanation underneath', async ({ page }) => {
  await page.goto('./');
  await page.getByTestId('subject-name').fill('Rivers');
  await page.getByTestId('add-subject').click();
  await expect(page.locator('[data-subject-name="Rivers"]')).toHaveClass(/on/);
  await page.getByTestId('pdf-file').setInputFiles(sampleThree);
  await page.getByTestId('save-tests').click();
  await page.locator('[data-deck-name="Practice Test 1"]').click();
  await page.getByTestId('start-untimed').click();
  await expect(page.getByTestId('result')).toHaveCount(0);
  await expect(page.getByTestId('explanation')).toHaveCount(0);
  await expect(page.getByTestId('watch-lesson')).toHaveCount(0);
  await expect(page.getByTestId('why')).toHaveCount(0);
  await expect(page.getByText('Cairo sits on the Nile')).toHaveCount(0);
  const choice = page.getByTestId('choice').filter({ hasText: 'Nile' });
  await expect(choice).not.toHaveClass(/correct|wrong/);
  const box = await choice.boundingBox();
  expect(box?.height ?? 0).toBeGreaterThanOrEqual(44);
  await choice.click();
  await expect(page.getByTestId('result')).toHaveText('Correct');
  await expect(choice).toHaveClass(/correct/);
  await expect(page.getByTestId('explanation')).toContainText('Cairo sits on the Nile');
  await expect(page.getByTestId('why')).toHaveCount(0);
  const lesson = page.getByTestId('watch-lesson');
  await expect(lesson).toBeVisible();
  await expect(lesson).toHaveAttribute('href', /example\.com\/lessons\/nile/);
  await expect(page.getByTestId('next')).toBeVisible();
  await page.waitForTimeout(600);
  await expect(page.getByTestId('position')).toHaveText(/Question 1 of/);
});

test('a wrong choice shows the correct answer, the PDF explanation, and the lesson', async ({ page }) => {
  await page.goto('./');
  await page.getByTestId('subject-name').fill('Rivers');
  await page.getByTestId('add-subject').click();
  await expect(page.locator('[data-subject-name="Rivers"]')).toHaveClass(/on/);
  await page.getByTestId('pdf-file').setInputFiles(sampleThree);
  await page.getByTestId('save-tests').click();
  await page.locator('[data-deck-name="Practice Test 1"]').click();
  await page.getByTestId('start-untimed').click();
  await page.getByTestId('choice').filter({ hasText: 'Amazon' }).click();
  await expect(page.getByTestId('result')).toHaveText('Incorrect');
  await expect(page.getByTestId('choice').filter({ hasText: 'Amazon' })).toHaveClass(/wrong/);
  await expect(page.getByTestId('choice').filter({ hasText: 'Nile' })).toHaveClass(/correct/);
  await expect(page.getByTestId('explanation')).toContainText('Cairo sits on the Nile');
  await expect(page.getByTestId('why')).toHaveCount(0);
  const lesson = page.getByTestId('watch-lesson');
  await expect(lesson).toHaveAttribute('target', '_blank');
  await expect(lesson).toHaveAttribute('rel', /noopener/);
  await expect(lesson).toHaveAttribute('href', /example\.com\/lessons\/nile/);
});

test('choose two submits only after two taps, and a missing explanation is stated', async ({ page }) => {
  await page.goto('./');
  await page.getByTestId('subject-name').fill('Rivers');
  await page.getByTestId('add-subject').click();
  await expect(page.locator('[data-subject-name="Rivers"]')).toHaveClass(/on/);
  await page.getByTestId('pdf-file').setInputFiles(sampleThree);
  await page.getByTestId('save-tests').click();
  await page.locator('[data-deck-name="Practice Test 1"]').click();
  await page.getByTestId('start-untimed').click();
  await page.getByTestId('choice').filter({ hasText: 'Nile' }).click();
  await page.getByTestId('next').click();
  await expect(page.getByTestId('result')).toHaveCount(0);
  await expect(page.getByTestId('explanation')).toHaveCount(0);
  await expect(page.getByText('both flow through Europe')).toHaveCount(0);
  await page.getByTestId('choice').filter({ hasText: 'Danube' }).click();
  await expect(page.getByTestId('submit')).toBeDisabled();
  await expect(page.getByTestId('result')).toHaveCount(0);
  await page.getByTestId('choice').filter({ hasText: 'Danube' }).click();
  await page.getByTestId('choice').filter({ hasText: 'Danube' }).click();
  await page.getByTestId('choice').filter({ hasText: 'Rhine' }).click();
  await expect(page.getByTestId('choose-count')).toContainText('2 of 2');
  await expect(page.getByTestId('submit')).toBeEnabled();
  await page.getByTestId('submit').click();
  await expect(page.getByTestId('result')).toHaveText('Correct');
  await expect(page.getByTestId('explanation')).toContainText('both flow through Europe');
  await expect(page.getByRole('button', { name: /^A\. Danube/ })).toHaveClass(/correct/);
  await expect(page.getByRole('button', { name: /^C\. Rhine/ })).toHaveClass(/correct/);
  await page.getByTestId('next').click();
  await expect(page.getByTestId('explanation')).toHaveCount(0);
  await page.getByTestId('choice').filter({ hasText: 'Madrid' }).click();
  await expect(page.getByTestId('result')).toHaveText('Incorrect');
  await expect(page.getByTestId('explanation')).toHaveText('No explanation provided in your PDF.');
  await expect(page.getByRole('button', { name: /^A\. Lisbon/ })).toHaveClass(/correct/);
  await expect(page.getByRole('button', { name: /^B\. Madrid/ })).toHaveClass(/wrong/);
});

test('a question figure from the PDF is shown before the answer', async ({ page }) => {
  await page.goto('./');
  await page.getByTestId('subject-name').fill('Color');
  await page.getByTestId('add-subject').click();
  await expect(page.locator('[data-subject-name="Color"]')).toHaveClass(/on/);
  await page.getByTestId('pdf-file').setInputFiles(sampleFigure);
  await page.getByTestId('save-tests').click();
  await page.locator('[data-deck-name="Practice Test 1"]').click();
  await page.getByTestId('start-untimed').click();
  await expect(page.getByTestId('question-figure')).toBeVisible();
  await expect(page.getByTestId('result')).toHaveCount(0);
  await expect(page.getByTestId('explanation-figure')).toHaveCount(0);
  await page.getByTestId('choice').filter({ hasText: 'Red' }).click();
  await expect(page.getByTestId('result')).toHaveText('Incorrect');
  await expect(page.getByTestId('explanation')).toContainText('square in the figure is green');
  await expect(page.getByTestId('question-figure')).toBeVisible();
});
